[theme]
base="light"


# Primary accent for interactive elements
primaryColor = '#ff6600'

# Background color for the main content area
backgroundColor = '#212529'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#343a40'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"